$ANSIBLE_VAULT;1.1;AES256
36343066353966653062336364323366363864386433653536633566356638363165336433333066
3038333634656133353537633833313037363936303335610a346366616439643033353236646434
31396566333861306338386566363466303637656638376166356339333364623030386333663838
3537386233373333300a636236633235333862343861366237333664313161396638656136653365
61343334613762373838373763663633383635333334323836326632643835396264323866326561
61313530373266353062663631366139393534656536383135363566643833666661336462613164
32333632306134303032336164636365363132666134343234346562343365616462643130393838
34613937313935303735663934326635343632363031343634336636646138306663666539353766
34626537363064383663626335313336623832346263643031363933306333363261383163366530
31636265383839343338633234666561623132626663666133393364666131643063396563646466
34376362653033316531636465346462663137653362663464346135303364633265646531363034
66343964353063356562656430333561323963613837333430613061626563666134643534636631
3136
